name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: my-app:${{ github.sha }}
      
      - name: Install EB CLI
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          pip3 install awsebcli --upgrade
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploy to AWS Elastic Beanstalk
        run: |
          eb init lu-api --platform "Docker" --region ${{ secrets.AWS_REGION }}
          eb use Luapi-env
          eb deploy --staged
